name: Build and Push Docker Image

on:
  push:
    branches:
      - main

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  REPO_NAME: amitest

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure Docker CLI
        uses: docker/login-action@v1
        with:
          registry: https://index.docker.io/v1/
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Create Docker Hub repository
        run: |
          curl -v -X POST \
            --header "Content-Type: application/json" \
            --data "{\"namespace\": \"${DOCKER_USERNAME}\", \"name\": \"${REPO_NAME}\", \"is_private\": false}" \
            --user "${DOCKER_USERNAME}:${DOCKER_PASSWORD}" \
            https://hub.docker.com/v2/repositories/

      - name: Build and tag Docker image
        run: |
          docker build --no-cache -f Dockerfile.pytest -t "amitest" .
          docker build --no-cache -f Dockerfile.pytest -t "ubuntu/${REPO_NAME}:${TAG}" .

      - name: Run tests in Docker container
        run: |
          docker run -u root:root --rm -it --name "JOB" \
            -e REGRESSION_HOME=/regression/ \
            -e PYTHONPATH=/regression/ \
            "${DOCKER_USERNAME}/${REPO_NAME}:${TAG}"
        env:
          TAG: ${{ matrix.tag }}
