name: Terraform Integration Checks

on:
  push:
    branches:
      - main
    paths:
      - "aviatrix/*.go"
  workflow_dispatch:
    inputs:
      branch_name:
        description: "Branch name if different from the current branch"
        required: false
        type: string

jobs:
  IntegrationTest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # Use the latest version of the checkout action
      - name: Setup Go
        uses: actions/setup-go@v2 # Use the latest version of the setup-go action
        with:
          go-version: "1.18.x"

      - uses: ReeganExE/github-action-job-id@v1.0
        with:
          expose-name: true
      - uses: jwalton/gh-find-current-pr@v1
        id: findPr
        with:
          state: open

      - name: Integration Test Check
        run: |
          git diff-tree --no-commit-id --name-only -r ${{ github.sha }} > changed_files.txt
          diffFiles=$(cat changed_files.txt)
          noNeedRun=true
          for fileName in ${diffFiles[@]}; do
              if [[ ${fileName} == "aviatrix/resource_aviatrix"* || ${fileName} == "aviatrix/data_source_aviatrix"* ]]; then
                  if [[ ${fileName} != *?_test.go ]]; then
                      fileName="${fileName//\.go/_test\.go}"
                  fi
                  echo -e "\n\033[37mChecking diff file $fileName ...\033[0m"
                  noNeedRun=false

                  if [[ $(grep -c "func TestAcc.*" ${fileName}) -lt 1 ]]; then
                    echo -e "\033[33m[WARNING] Missing acceptance test cases in the file $fileName, continue..."
                    continue
                  fi

                  checkFuncs=$(grep "func TestAcc.*" ${fileName})
                  echo -e "found the test funcs:\n${checkFuncs}\n"
                  funcs=(${checkFuncs//"(t *testing.T) {"/ })
                  for func in ${funcs[@]}; do
                    if [[ ${func} != "TestAcc"* ]]; then
                      continue
                    fi
                    DiffFuncNames+="${func};"
                  done
              fi
          done

          if [[ "${noNeedRun}" = "false" && -z "${DiffFuncNames}" ]]; then
              echo -e "\n\033[33m[WARNING] Missing integration test cases, please add them."
              exit 1
          fi

          if [[ "${noNeedRun}" = "true" ]]; then
              echo -e "\n\033[33m[WARNING] The PR does not need to run integration tests."
              exit 0
          fi
