name: Terraform Integration Checks

on:
  push:
    paths:
      - 'aviatrix/*.go'

jobs:
  IntegrationTest:
    runs-on: ubuntu-latest
    needs: DocsExampleTest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.18.x'

      - name: Get Current PR
        id: findPr
        uses: jwalton/gh-find-current-pr@v1
        with:
          state: open

      - name: Checkout PR Branch
        if: steps.findPr.outputs.pr_number != ''
        run: |
          pr_number="${{ steps.findPr.outputs.pr_number }}"
          git fetch origin pull/${pr_number}/head:pr/${pr_number}
          git checkout "pr/${pr_number}"

      - name: List Changed Files
        run: |
          # List all changed files
          git diff --name-only HEAD^ HEAD

      - name: Integration Test Check
        run: |
          # Diff the changed files
          diffFiles=$(git diff --name-only HEAD^ HEAD)
          noNeedRun=true
          DiffFuncNames=""
          
          for fileName in ${diffFiles[@]}; do
              if [[ ${fileName} == "aviatrix/resource_aviatrix"* || ${fileName} == "aviatrix/data_source_aviatrix"* ]]; then
                  if [[ ${fileName} != *?_test.go ]]; then
                      fileName=(${fileName//\.go/_test\.go })
                  fi
                  echo -e "\n\033[37mChecking diff file $fileName ...\033[0m"
                  noNeedRun=false

                  if [[ $(grep -c "func TestAcc.*" ${fileName}) -lt 1 ]]; then
                    echo -e "\033[33m[WARNING] Missing acceptance test cases in the file $fileName, continue...\033[0m"
                    continue
                  fi

                  checkFuncs=$(grep "func TestAcc.*" ${fileName})
                  echo -e "Found the test funcs:\n${checkFuncs}\n"
                  funcs=(${checkFuncs//"(t *testing.T) {"/ })
                  for func in ${funcs[@]}; do
                    if [[ ${func} != "TestAcc"* ]]; then
                      continue
                    fi
                    DiffFuncNames="${DiffFuncNames};${func}"
                  done
              fi
          done

          if [[ "${noNeedRun}" = "false" && ${DiffFuncNames} == "" ]]; then
              echo -e "\n\033[33m[WARNING] Missing integration test cases, please add them.\033[0m"
              exit 1
          fi
          
          if [[ "${noNeedRun}" = "true" ]]; then
              echo -e "\n\033[33m[WARNING] The PR does not need to run integration tests.\033[0m"
              exit 0
          fi

          # Additional debugging logs for information
          echo -e "\nDebugging Information:"
          echo "PR URL: ${{ steps.findPr.outputs.pr_url }}"
          echo "DiffFuncNames: ${DiffFuncNames}"

          # You can add more debugging logs here as needed

          # Run your integration tests here
          # ...

